# General Deployment Config
stack_install_dir: "/opt/tools_stack"
stack_user: "root"
stack_group: "root"

# versions (Pinning for security)
version_it_tools: "2024.5.13-7467652"
version_cyberchef: "v10.19.2"
version_drawio: "24.4.13"
version_excalidraw: "latest"
version_bentopdf: "latest"
version_plantuml: "jetty-v1.2024.5"
version_mermaid: "v10.8.0"
version_convertx: "v0.15.1"
version_omni_tools: "latest"
version_bytestash: "1.5.9"
version_memos: "0.25.3"
version_freshrss: "latest"
version_booklore: "latest"
version_booklore_mariadb: "11.4.5"

# Ports
port_it_tools: "8080"
port_cyberchef: "8081"
port_diagrams: "8082"
port_excalidraw: "8083"
port_bentopdf: "8084"
port_plantuml: "8085"
port_mermaid: "8086"
port_convertx: "8087"
port_omni_tools: "8088"
port_bytestash: "8089"
port_memos: "8090"
port_freshrss: "8091"
port_booklore: "8092"

# Secret (Leave empty to auto-generate on first run)
convertx_jwt_secret: ""

# Bytestash
bytestash_data_dir: "/bytestash/data"
bytestash_base_path: ""
bytestash_jwt_secret: "CHANGE_ME"
bytestash_token_expiry: 24h
bytestash_allow_new_accounts: "false"
bytestash_debug_enabled: "false"
bytestash_disable_accounts: "true"
bytestash_disable_internal_accounts: "false"
bytestash_oidc_enabled: "false"

# Memos
memos_data_dir: "/memos"

# FreshRSS
memos_extensions_dir: "/freshrss/extensions"

# Booklore
booklore_dir: "/booklore"
booklore_db_root_password: "CHANGE_ME"
booklore_db_password: "CHANGE_ME"