apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: netshoot
  name: netshoot
spec:
  containers:
  - image: nicolaka/netshoot
    name: netshoot
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
