$ANSIBLE_VAULT;1.1;AES256
38656534316465633932356262613566346161656162653534373937663834653331373937613764
6532316135313239653864366537663262643261613231620a376237343631333661303032623836
38303435393135623061653735663432353365646536646236663937323239633737366561613365
3832663231303636350a623839636432363831373435363730663264383535643230376434386562
34316139313230623434636665353038646136376361306531326231336332633932653636366232
32626234383866636531313531336332303466633438373534336636646564306530303733366138
66363864663130613632626362643338323437646437663762383535353331383766303732363664
31333162333130623435393338666364323931653337343439653961656335316237383061363164
63623335653638616364303831333631373533363334626336333839333634376261
