services:
  docker-in-docker:
    image: docker:29.1.3-dind@sha256:173f284a4299164772a90f52b373e73e087583c0963f1334c9995f190ef6f3f5
    container_name: forgejo-dind
    privileged: 'true'
    command: ['dockerd', '-H', 'tcp://0.0.0.0:2375', '--tls=false']
    restart: 'unless-stopped'

  runner:
    image: "code.forgejo.org/forgejo/runner:12.3.1"
    container_name: 'forgejo-runner'
    links:
      - docker-in-docker
    depends_on:
      docker-in-docker:
        condition: service_started
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    # User without root privileges, but with access to `./data`.
    user: 1000:1000
    volumes:
    - forgejo-runner-data:/data
    - /opt/forgejo-runner/config.yaml:/config.yaml
    restart: 'unless-stopped'
    # command: '/bin/sh -c "sleep 5; forgejo-runner daemon"
    command: '/bin/sh -c "sleep 5; forgejo-runner daemon --config /config.yaml"'

volumes:
  forgejo-runner-data:
    external: true