forgejo_http_port: 3000
forgejo_db_type: "sqlite3"
forgejo_app_name: "Forgejo"
forgejo_run_mode: "prod"

forgejo_domain: "{{ vault_forgejo_domain }}"
forgejo_admin_user: "{{ vault_admin_user }}" 
forgejo_admin_password: "{{ vault_admin_password }}"
forgejo_admin_email: "{{ vault_admin_email }}"
forgejo_secret_key: "{{ vault_forgejo_secret_key }}"