---
- name: Setup security core
  hosts: security_core 
  become: true

  roles:
    - role: docker_install
    - role: authentik
      tags: app
      vars:
        authentik_secret_key: "{{ vault_authentik_secret }}"
        authentik_pg_pass: "{{ vault_postgres_pass }}"
        authentik_version: "2025.10.4"
        enable_cloudflare_tunnel: true
        cloudflare_tunnel_token: "{{ vault_tunnel_token }}"