- hosts: tools-stack 
  roles:
    - docker_install
    - tools_stack
  vars:
    version_it_tools: 2024.10.22-7ca5933
    version_cyberchef: 10.19@sha256:a2bfe382b2547bdd0a3d0523b9a6b85fab833c56bcec86d600ba6266910b533e
    version_drawio: 29.2.9@sha256:3169171c1c5ad1dc4d0c7096afd59b8aa997833f790c1427db97b7fd8f1a3be4
    version_excalidraw: latest@sha256:95d528cb4f8d18e0fbdc42ae3d09b5c4a899bfbd6bb89eeaf94b904330d79714
    version_bentopdf: v1.11.2@sha256:36ff37a6cee580a912cba423090324a909f098ad5d5213cfafbd15846ee268ee
    version_plantuml: v1.2025.10@sha256:ac656ab4215fd80554c59330fd365a3b29041e317f232563c7fc807680ec4ef0
    version_mermaid: sha256-396e4a1d5913cd906dc59e59d83c0eb322a5dd2aa2f5763af664a01bfe0bcf92
    version_convertx: v0.16.1@sha256:a7b961295ceba0b852848108e94aac037d30f6687419be7cb58e392023529610
