forgejo_version: "10.0.1"
forgejo_user: "git"
forgejo_group: "git"
forgejo_home: "/var/lib/forgejo"
forgejo_config_dir: "/etc/forgejo"
forgejo_bin_path: "/usr/local/bin/forgejo"

forgejo_arch: "linux-amd64"
forgejo_download_url: "https://codeberg.org/forgejo/forgejo/releases/download/v{{ forgejo_version }}/forgejo-{{ forgejo_version }}-{{ forgejo_arch }}"
