# Generate docker-compose locally
- name: Ensure local directory exists for generated compose
  file:
    path: "generated/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false
  tags:
  - local
  - debug

- name: Render docker-compose.yml locally
  template:
    src: docker-compose.yml.j2
    dest: "generated/{{ inventory_hostname }}/docker-compose-{{role_name}}.yml"
  delegate_to: localhost
  become: false
  tags:
  - local
  - debug


# Set up app
# Remote host
- name: Ensure Paperless directories exist
  file:
    path: "{{ paperless_dir }}/{{ item }}"
    state: directory
    # owner: "{{ stack_user }}"
    # group: "{{ stack_group }}"
    mode: "0755"
  loop:
    - export
    - consume

- name: Deploy .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ paperless_dir }}/.env"
    mode: '0600'

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ paperless_dir }}/docker-compose.yml"
    # owner: "{{ stack_user }}"
    # group: "{{ stack_group }}"
    mode: '0640'
  # notify: Restart Docker Stack

- name: Ensure Docker Compose is up and running
  community.docker.docker_compose_v2:
    project_src: "{{ paperless_dir }}"
    state: present
    pull: missing
    remove_orphans: true