# --- image versions ---
paperless_webserver_image: ghcr.io/paperless-ngx/paperless-ngx:2.20.7
paperless_broker_image: redis:7.4.7
paperless_db_image: postgres:15.16

# --- paperless config ---
paperless_dir: /opt/paperless
paperless_web_port: 8000
paperless_secret_key: "changeme"
paperless_time_zone: UTC

# --- paperless admin user ---
paperless_admin_user: admin
paperless_admin_password: admin
paperless_admin_email: admin@example.com

# --- paperless db config ---
paperless_db_name: paperless
paperless_db_user: paperless
paperless_db_password: paperless
paperless_db_port: 5432

# --- paperless redis config ---
paperless_redis_port: 6379
