# https://hub.docker.com/_/mongo
# How to use this image via docker-compose
version: "3"
services:
  mongo:
    image: mongo:7
    # Check command options: docker run -it --rm mongo --hel
    # or: https://www.mongodb.com/docs/manual/reference/program/mongod/    
    # command: --serviceExecutor adaptive
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - "127.0.0.1:27017:27017"
    volumes:
    - type: volume
      source: mongodata
      target: /data/db

# https://hub.docker.com/_/mongo-express
# Auth default to admin:pass
# ME_CONFIG_MONGODB_AUTH_USERNAME
# ME_CONFIG_MONGODB_AUTH_PASSWORD
  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


volumes:
  mongodata:
