- name: Set up Authentik base directory
  ansible.builtin.file:
    path: "{{ authentik_base_dir }}"
    state: directory
    mode: '0755'

- name: Deploy .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ authentik_base_dir }}/.env"
    mode: '0600'
  # notify: Restart Authentik

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ authentik_base_dir }}/docker-compose.yml"
    mode: '0644'
  # notify: Restart Authentik

- name: Bring up stack
  community.docker.docker_compose_v2:
    project_src: "{{ authentik_base_dir }}"
    state: present
    pull: always
