# Generate docker-compose locally
- name: Ensure local directory exists for generated compose
  file:
    path: "generated/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false

- name: Render docker-compose.yml locally
  template:
    src: docker-compose.yml.j2
    dest: "generated/{{ inventory_hostname }}/docker-compose-{{ role_name }}.yml"
  delegate_to: localhost
  become: false
  tags:
  - generate

# Remote host
- name: Set up application base directory
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ stack_user }}"
    group: "{{ stack_group }}"
    mode: '0755'

- name: Deploy .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ install_dir }}/.env"
    mode: '0600'

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ install_dir }}/docker-compose.yml"
    owner: "{{ stack_user }}"
    group: "{{ stack_group }}"
    mode: '0640'
  notify: Restart Docker Stack

- name: Create data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  loop:
    - "{{ install_dir }}/data"

- name: Ensure Docker Compose is up and running
  community.docker.docker_compose_v2:
    project_src: "{{ install_dir }}"
    state: present
    pull: missing
    remove_orphans: true