apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kind-01-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/kind-01
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system