services:

  # ---------------------------------------------------------
  # TSDB
  # ---------------------------------------------------------
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.133.0-scratch
    container_name: victoriametrics
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - vm_data:/storage
    ports:
      - "8428:8428"
    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=1y" # Default is 1 month
      - "-httpListenAddr=:8428"
    networks:
      - monitoring

  # ---------------------------------------------------------
  # LOGS
  # ---------------------------------------------------------
  loki:
    image: grafana/loki:3.6
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
    - monitoring

  # ---------------------------------------------------------
  # Data Visualization
  # ---------------------------------------------------------
  grafana:
    image: grafana/grafana:12.3.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - /opt/monitoring/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_ANALYTICS_REPORTING_ENABLED=false  
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false     
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
    depends_on:
      - victoriametrics
      - loki
    networks:
      - monitoring

  # ---------------------------------------------------------
  # Proxmox Data Exporter
  # ---------------------------------------------------------
  pve-exporter:
    image: prompve/prometheus-pve-exporter:3.8.1
    restart: unless-stopped
    ports:
      - "9221:9221"
    environment:
      - PVE_USER=${PVE_USER}
      - PVE_TOKEN_NAME=${PVE_TOKEN_NAME}
      - PVE_TOKEN_VALUE=${PVE_TOKEN_VALUE}
      - PVE_VERIFY_SSL=False
    networks:
      - monitoring

  # ---------------------------------------------------------
  # Data Agent
  # ---------------------------------------------------------
  cadvisor:
    image: ghcr.io/google/cadvisor:0.56.2
    container_name: external_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    devices:
      - /dev/kmsg # detect OOM
#    ports:
#      - "8078:8080"
    privileged: true
    networks:
      - monitoring

  alloy:
    image: grafana/alloy:v1.13.1
    container_name: alloy
    hostname: "srv-prod-01"
    restart: unless-stopped
    # Requires privileges to get logs and metrics from host
    user: root
    pid: host
    privileged: true #cAdvisor
    #cap_add:
    #  - SYS_PTRACE       # Useful for profiling
    #  - DAC_READ_SEARCH
    volumes:
      # Configuration and data (WAL)
      - /opt/monitoring/config/alloy/config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy/data

      # Docker access (to find out containers logs/metrics)
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # Host metrics
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /:/host/root:ro

      # Host logs 
      - /var/log/journal:/var/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro # Required for journald
    environment:
      # These are optional. They are defined on config.alloy
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ROOT=/host/root
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data --disable-reporting /etc/alloy/config.alloy
    ports:
      - "12345:12345" # Debug UI
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # MÃ¡ximo 10 MB per file
        max-file: "3"
    depends_on:
      - victoriametrics
      - loki
    networks:
      - monitoring
    

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data: {}
  vm_data: {}
  loki_data: {}
  alloy_data: {}
