- name: Update apt cache and install necessary packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  when: ansible_facts["os_family"] == "Debian"

- name: Add Docker GPG apt key
  ansible.builtin.get_url:
    url: "{{ docker_repo_url }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes # Ensure the latest key is downloaded
  when: ansible_facts["os_family"] == "Debian"

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ 'amd64' if ansible_facts["architecture"] == 'x86_64' else 'arm64' if ansible_facts["architecture"] == 'aarch64' else 'armhf' }} signed-by=/etc/apt/keyrings/docker.asc]
      {{ docker_repo_url }}
      {{ ansible_facts["distribution_release"] }}
      stable
    state: present
    filename: docker
  when: ansible_facts["os_family"] == "Debian" 

- name: Define core and optional Docker packages
  ansible.builtin.set_fact:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Conditionally add Docker plugins to the installation list
  ansible.builtin.set_fact:
    docker_packages: "{{ docker_packages + ['docker-compose-plugin'] }}"
  when: install_docker_plugins | bool

- name: Install Docker Engine
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: true
  when: ansible_facts["os_family"] == "Debian"

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  notify: Reconnect SSH
